name: my_first_package
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  calculator:
    path: 'packages/calculator'
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
